### ISSUE TITLE
VCF Format Änderung

### ISSUE THREAD

**Issue by cruckert** [GC-HBOC/HowTo_Calculation_PRS_CanRisk#1]
Scheinbar hat sich seit dem letzten Update verändert, wie Dosage Zeilen in der VCF Datei angegeben werden müssen:

1	100880328	A	T	.	.	.	DS	0.8200

hat bei mir nicht mehr funktioniert, stattdessen ging aber

1	100880328	A	T	.	.	.	GT:DS	./.:0.8200

**Comment by CorinnaErnst** [comment]
Danke dir und habe es geändert. 
Du hättest aber auch gern einfach ergänzen können. Imho haben alle Schreibrechte.
