### ISSUE TITLE
OCAC36 liftover

### ISSUE THREAD

**Issue by StephanHolgerD** [GC-HBOC/HowTo_Calculation_PRS_CanRisk#4]
Hallo, 
vielleicht ist das ein bisschen random, aber ich glaube im  https://github.com/GC-HBOC/HowTo_Calculation_PRS_CanRisk/blob/main/hg38/OCAC_36.vcf gibt es potentiell einen fehlerhaften liftover bei:

```
17	36100767	.	A	G	.	.	POP_AF=0.6019;WEIGHT=-0.0582;hg19_var=17_36100767_A_G;comment=Lifted%20through%20dbSNP%20id%20by%20hand(rs11657964)
```
Hier sind HG19 und HG39 Pos in der vcf identisch

https://www.ncbi.nlm.nih.gov/snp/?term=rs11657964

Ich weiss nicht ob jemand den OCAC 36 PRS auf HG38 nutzt aber da waere das vllt relevant. .

**Comment by marc-sturm** [comment]
Hi Stephan,

danke, wir korrigieren das sobald wir alle SNPs nochmal überprüft haben.

Viele Grüße,
  Marc
